const {days,stays,reservations}=window.TRIP;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p);
const week=['日','一','二','三','四','五','六'];
const shortCities=['馬賽','馬賽','阿爾勒','山城市集','酒莊','聖十字湖','峽谷・尼斯','蔚藍海岸','坎城','返程'];
function parisDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
const actualDay=()=>days.findIndex(d=>d.date===parisDate());
let day=Math.max(0,actualDay()),stop=0;
const hashMatch=location.hash.match(/^#day-(\d+)(?:-stop-(\d+))?$/);
if(hashMatch){day=Math.min(9,Math.max(0,Number(hashMatch[1])-1));stop=Math.min(days[day].events.length-1,Math.max(0,Number(hashMatch[2]||1)-1))}
function status(s){if(!s)return '';const pending=/待|尚未|未確認/.test(s);const confirmed=/已預約|已確認|已訂|已安排/.test(s);return `<span class="badge ${pending?'pending':confirmed?'':'neutral'}">${esc(s)}</span>`}
function setHash(){history.replaceState(null,'',`#day-${day+1}-stop-${stop+1}`)}
function showView(view){document.querySelectorAll('[data-view]').forEach(b=>{const selected=b.dataset.view===view;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});['itinerary','stays','bookings'].forEach(id=>$('#'+id).hidden=id!==view)}
function chooseDay(i){day=i;stop=0;setHash();render();$('.date.active').scrollIntoView({block:'nearest',inline:'center'})}
function chooseStop(i,scroll=false){stop=i;setHash();renderFocus();document.querySelectorAll('.event').forEach((el,j)=>el.classList.toggle('selected',j===stop));if(scroll)$('#focus').scrollIntoView({behavior:'smooth',block:'start'})}
function currentStay(){return stays[day<2?0:day<4?1:day===4?2:day===5?3:4]}
function renderFocus(){const d=days[day],e=d.events[stop],stay=currentStay(),ended=day===9&&stop===d.events.length-1;$('#focus').innerHTML=`<div class="focus-card"><div class="focus-label">${day===actualDay()?'今天的行程':'行程預覽'}<span>${d.label} · 第 ${stop+1} / ${d.events.length} 站</span></div><p class="focus-time">${esc(e.time)}</p><h3>${esc(e.title)}</h3>${status(e.status)}<p class="focus-place">${esc(e.place)}</p>${e.transport?`<p class="focus-place">交通：${esc(e.transport)}</p>`:''}${e.note?`<p class="focus-note">${esc(e.note)}</p>`:''}<div class="focus-actions"><a class="map-button" href="${map(e.place||e.title)}" target="_blank" rel="noopener noreferrer">開啟地圖 ↗</a><button id="advance" class="secondary" ${ended?'disabled':''}>${stop===d.events.length-1?'看隔天行程':'下一站 →'}</button></div><div class="focus-nav"><button id="back-stop" ${stop===0?'disabled':''}>← 上一站</button><button id="in-timeline">在時間軸查看 ↓</button></div></div><div class="stay-mini"><p class="eyebrow">${day===9?'今日退房':'今晚住宿'}</p><p>${esc(stay[1])}</p><a href="${map(stay[2])}" target="_blank" rel="noopener noreferrer">${esc(stay[2])} ↗</a></div>`;$('#advance').onclick=()=>{if(stop<d.events.length-1)chooseStop(stop+1);else if(day<9)chooseDay(day+1)};$('#back-stop').onclick=()=>chooseStop(stop-1);$('#in-timeline').onclick=()=>$('#event-'+stop).scrollIntoView({behavior:'smooth',block:'center'})}
function render(){$('#dates').innerHTML=days.map((d,i)=>`<button class="date ${i===day?'active':''}" aria-pressed="${i===day}" data-day="${i}" aria-label="${d.label} 星期${week[new Date(d.date+'T12:00:00').getDay()]} ${d.title}"><small>DAY ${String(i+1).padStart(2,'0')}</small><strong>${d.label}</strong><span>${shortCities[i]}</span></button>`).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>chooseDay(+b.dataset.day));const d=days[day];$('#day-city').textContent=d.city;$('#day-title').textContent=d.title;$('#day-number').textContent=String(day+1).padStart(2,'0');$('#alerts').innerHTML=d.alerts.map(a=>`<div class="alert">${esc(a)}</div>`).join('');$('#timeline').innerHTML=d.events.map((e,i)=>`<article id="event-${i}" class="event ${i===stop?'selected':''}"><div class="event-time">${esc(e.time)}</div><div class="event-body"><button class="event-title" data-stop="${i}" aria-label="查看第 ${i+1} 站：${esc(e.title)}">${esc(e.title)}</button><div class="event-meta">${e.transport?`<span>${esc(e.transport)}</span>`:''}${status(e.status)}</div><details><summary>地點與提醒</summary><p>${esc(e.place)}</p>${e.note?`<p>${esc(e.note)}</p>`:''}<a href="${map(e.place||e.title)}" target="_blank" rel="noopener noreferrer">開啟地圖 ↗</a></details></div></article>`).join('');document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>chooseStop(+b.dataset.stop,true));$('#prev-day').disabled=day===0;$('#next-day').disabled=day===9;renderFocus()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#prev-day').onclick=()=>{chooseDay(day-1);$('#dates').scrollIntoView({block:'start'})};$('#next-day').onclick=()=>{chooseDay(day+1);$('#dates').scrollIntoView({block:'start'})};let toastTimer;$('#today').onclick=()=>{const i=actualDay();if(i>=0){chooseDay(i);toast('已切換至法國當地日期；可點下一站依實際進度查看。')}else{chooseDay(parisDate()<days[0].date?0:9);toast(parisDate()<days[0].date?'旅程將於 10/8 開始，先看看第一天。':'旅程已結束，現在顯示最後一天。')}};function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500)}
$('#stay-list').innerHTML=stays.map(s=>`<article class="info-card"><span class="date-label">${esc(s[0])}</span>${status(s[4])}<h3>${esc(s[1])}</h3><p>${esc(s[2])}</p><p>${esc(s[3])} · ${esc(s[5])}</p><a href="${map(s[2])}" target="_blank" rel="noopener noreferrer">住宿地圖 ↗</a></article>`).join('');
$('#pending-count').textContent=reservations.filter(r=>/待|尚未/.test(r[2])).length;
$('#booking-list').innerHTML=reservations.map(r=>`<article class="info-card"><span class="date-label">${esc(r[0])}</span>${status(r[2])}<h3>${esc(r[1])}</h3><p>${esc(r[3])}</p><p>${esc(r[4])}</p></article>`).join('');
$('#all-alerts').innerHTML=days.filter(d=>d.alerts.length).map(d=>`<div class="alert"><strong>${d.label} 安排提醒</strong><br>${d.alerts.map(esc).join('<br>')}</div>`).join('');
render();
